name: build boots

on:
  push:
    branches: [base, nvidia, rocm, printer]
  workflow_dispatch: {}

jobs:
  build-iso:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavor: base
            nvidia: "0"
            rocm: "0"
            printer: "0"
          - flavor: nvidia
            nvidia: "1"
            rocm: "0"
            printer: "0"
          - flavor: rocm
            nvidia: "0"
            rocm: "1"
            printer: "0"
          - flavor: printer
            nvidia: "0"
            rocm: "0"
            printer: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo -S -p '' apt-get update -qq
          sudo -S -p '' apt-get install -y -qq podman

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (${{ matrix.flavor }})
        run: |
          podman build \
            --build-arg WITH_NVIDIA=${{ matrix.nvidia }} \
            --build-arg WITH_ROCM=${{ matrix.rocm }} \
            --build-arg WITH_PRINTER=${{ matrix.printer }} \
            --file Containerfile \
            --tag ghcr.io/swam-web/mon-bootc:${{ matrix.flavor }} .
          podman push ghcr.io/swam-web/mon-bootc:${{ matrix.flavor }}

      - name: Generate ISO (${{ matrix.flavor }})
        uses: osbuild/bootc-image-builder-action@v0.0.2
        id: build-iso
        with:
          image: ghcr.io/swam-web/mon-bootc:${{ matrix.flavor }}
          types: |
            anaconda-iso
          config-file: ./build/config.toml
          rootfs: btrfs

      - name: Upload ISO (${{ matrix.flavor }})
        uses: actions/upload-artifact@v4
        with:
          name: mon-bootc-${{ matrix.flavor }}
          path: ${{ steps.build-iso.outputs.output-directory }}
