name: build boots

on:
  push:
    branches: [base, nvidia, rocm, printer]
  workflow_dispatch: {}

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build bootc image (base)
        run: |
          chmod +x ./build/build.sh
          SKIP_ISO=1 SKIP_ISO=1 ./build/build.sh localhost/mon-bootc:latest base
  
  build-nvidia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build bootc image (nvidia)
        run: |
          chmod +x ./build/build.sh
          SKIP_ISO=1 SKIP_ISO=1 WITH_Nvidia=1 ./build/build.sh localhost/mon-bootc:nvidia nvidia
  
  build-rocm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build bootc image (rocm)
        run: |
          chmod +x ./build/build.sh
          SKIP_ISO=1 SKIP_ISO=1 WITH_ROCM=1 ./build/build.sh localhost/mon-bootc:rocm rocm
  
  build-printer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build bootc image (printer)
        run: |
          chmod +x ./build/build.sh
          SKIP_ISO=1 SKIP_ISO=1 WITH_PRINTER=1 ./build/build.sh localhost/mon-bootc:printer printer
